/**
 * Created by mauricio on 5/11/15.
 */
'use strict';
var Interval = require('./Interval');

//Boost Software License - Version 1.0 - August 17th, 2003
//
//Permission is hereby granted, free of charge, to any person or organization
//obtaining a copy of the software and accompanying documentation covered by
//this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//Software, and to permit third-parties to whom the Software is furnished to
//do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//all derivative works of the Software, unless such copies or derivative
//works are solely in the form of machine-executable object code generated by
//a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//DEALINGS IN THE SOFTWARE.

var piLow = (3373259426.0 + 273688.0 / (1 << 21)) / (1 << 30);
var piHigh = (3373259426.0 + 273689.0 / (1 << 21)) / (1 << 30);

var constants = {};

constants.PI_LOW = piLow;
constants.PI_HIGH = piHigh;
constants.PI_HALF_LOW = piLow / 2;
constants.PI_HALF_HIGH = piHigh / 2;
constants.PI_TWICE_LOW = piLow * 2;
constants.PI_TWICE_HIGH = piHigh * 2;

// intervals
constants.PI = new Interval(piLow, piHigh);
constants.PI_HALF = new Interval(constants.PI_HALF_LOW, constants.PI_HALF_HIGH);
constants.PI_TWICE = new Interval(constants.PI_TWICE_LOW, constants.PI_TWICE_HIGH);
constants.ONE = new Interval(1, 1);
constants.WHOLE = new Interval().setWhole();
constants.EMPTY = new Interval().setEmpty();

module.exports = constants;
